// integrations/supabase/client.ts
// This file is automatically generated. Do not edit it directly.

import { createClient, type SupabaseClient } from '@supabase/supabase-js'
import type { Database } from './types'
import { logger } from "@/lib/logger";

// Variables de entorno (Vite expone solo vars con prefijo VITE_ al navegador):
//   VITE_SUPABASE_URL         → URL del proyecto Supabase
//   VITE_SUPABASE_ANON_KEY    → clave pública anónima (o publishable key)
//
// Fallbacks:
//   NEXT_PUBLIC_*            → compatibilidad Next.js multi-entorno
//   DATABASE_SUPABASE_*      → Vercel Supabase integration (solo server-side;
//                              en cliente Vite serán undefined; configurar
//                              VITE_SUPABASE_* en Vercel env vars aparte)

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ??
  import.meta.env.VITE_NEXT_PUBLIC_SUPABASE_URL

const SUPABASE_ANON_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ??
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  import.meta.env.VITE_NEXT_PUBLIC_SUPABASE_ANON_KEY

const isDev = import.meta.env.DEV

// Storage seguro (browser vs Workers/SSR).
const storage =
  typeof window !== 'undefined' && typeof window.localStorage !== 'undefined'
    ? window.localStorage
    : undefined

if ((!SUPABASE_URL || !SUPABASE_ANON_KEY) && isDev) {
  logger.warn(
    '[supabase] Configuración incompleta: asegúrate de definir ' +
    'VITE_SUPABASE_URL y VITE_SUPABASE_ANON_KEY en .env.development.local.',
  )
}

// Declaración global para singleton (Vite HMR safe).
declare global {
  var __supabase__: SupabaseClient<Database> | undefined
}

function createSupabaseClient(): SupabaseClient<Database> {
  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    const MISSING_MSG =
      '[supabase] Configuración incompleta. Define VITE_SUPABASE_URL y VITE_SUPABASE_ANON_KEY ' +
      'en .env.local, o configura DATABASE_SUPABASE_URL y DATABASE_SUPABASE_ANON_KEY ' +
      'en las variables de entorno de Vercel (Supabase Integration).'

    if (isDev) {
      logger.error(MISSING_MSG)
    }

    // Stub client — no crashea la app, pero devuelve errores claros en auth.
    return createClient<Database>('https://placeholder.supabase.co', 'placeholder-key', {
      auth: { persistSession: false },
    })
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      storage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  })
}

// Singleton protegido con globalThis.
export const supabase: SupabaseClient<Database> =
  globalThis.__supabase__ ?? createSupabaseClient()

globalThis.__supabase__ = supabase

// Importa el cliente así desde el resto del proyecto:
//
//   import { supabase } from '@/integrations/supabase/client'
//
// Cualquier error de configuración se manifestará al inicializar el módulo,
// no en puntos aleatorios de la ejecución.
